name: SQL Prodecure
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - shell: python
      - uses: actions/checkout@v4
      - name: Run the procedure given
        run: |
          python exec_procedure.py
          print("Procedure ran successfully")
        
