name: SQL Procedure
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v4
      - name: Install the dependecies
        run : |
         sudo apt update
         sudo apt install -y unixodbc-dev
         sudo apt install -y odbcinst odbcinst1debian2 odbc-bin unixodbc
         sudo apt install -y msodbcsql17
         pip install pyodbc
      - name: Run the procedure
        run: |
             python exec_procedure.py
             echo "Procedure ran successfully"
        
